import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Header from "@/Components/header";
import Footer from "@/Components/footer";
config.autoAddCss = false


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StartAusbildung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-hide `}
      >
        <NextIntlClientProvider locale="fr">
     <section className=" w-full ">
            <Header />
        </section>
      <NextIntlClientProvider >{children}</NextIntlClientProvider>
       <section className="h-[210px] bg-[#111827]">
              <Footer/>
            </section>
            </NextIntlClientProvider>
      </body>
    </html>
  );
}


